# myapp/management/commands/fill_countries.py
from django.core.management.base import BaseCommand
from dash.models import Country, Currency

COUNTRY_DATA = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Angola": "AO",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Belarus": "BY",
    "Belgium": "BE",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Cayman Islands": "KY",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominican Republic": "DO",
    "East Timor": "TL",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Ethiopia": "ET",
    "Euro Area": "EA",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kosovo": "XK",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macau": "MO",
    "Macedonia": "MK",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palestine": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Republic of the Congo": "CD",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Swaziland": "SZ",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Togo": "TG",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}

class Command(BaseCommand):
    help = "Populate Country table with predefined countries and ISO codes."

    def handle(self, *args, **kwargs):
        for name, iso in COUNTRY_DATA.items():
            obj, created = Country.objects.update_or_create(
                iso_code=iso,
                defaults={'name': name}
            )
            action = "Created" if created else "Updated"
            self.stdout.write(f"{action} {name} ({iso})")

        self.stdout.write("Done.")


Currency.objects.bulk_create([
    Currency(code='USD', name='US Dollar', symbol='$'),
    Currency(code='EUR', name='Euro', symbol='€'),
    Currency(code='JPY', name='Japanese Yen', symbol='¥'),
    Currency(code='GBP', name='British Pound', symbol='£'),
    Currency(code='AUD', name='Australian Dollar', symbol='A$'),
    Currency(code='CAD', name='Canadian Dollar', symbol='C$'),
    Currency(code='CHF', name='Swiss Franc', symbol='CHF'),
    Currency(code='CNY', name='Chinese Yuan', symbol='¥'),
    Currency(code='HKD', name='Hong Kong Dollar', symbol='HK$'),
    Currency(code='NZD', name='New Zealand Dollar', symbol='NZ$'),
    Currency(code='SEK', name='Swedish Krona', symbol='kr'),
    Currency(code='KRW', name='South Korean Won', symbol='₩'),
    Currency(code='SGD', name='Singapore Dollar', symbol='S$'),
    Currency(code='NOK', name='Norwegian Krone', symbol='kr'),
    Currency(code='MXN', name='Mexican Peso', symbol='$'),
    Currency(code='INR', name='Indian Rupee', symbol='₹'),
    Currency(code='RUB', name='Russian Ruble', symbol='₽'),
    Currency(code='ZAR', name='South African Rand', symbol='R'),
    Currency(code='TRY', name='Turkish Lira', symbol='₺'),
    Currency(code='BRL', name='Brazilian Real', symbol='R$'),
    Currency(code='TWD', name='New Taiwan Dollar', symbol='NT$'),
    Currency(code='DKK', name='Danish Krone', symbol='kr'),
    Currency(code='PLN', name='Polish Zloty', symbol='zł'),
    Currency(code='THB', name='Thai Baht', symbol='฿'),
    Currency(code='IDR', name='Indonesian Rupiah', symbol='Rp'),
    Currency(code='HUF', name='Hungarian Forint', symbol='Ft'),
    Currency(code='CZK', name='Czech Koruna', symbol='Kč'),
    Currency(code='ILS', name='Israeli New Shekel', symbol='₪'),
    Currency(code='CLP', name='Chilean Peso', symbol='$'),
    Currency(code='PHP', name='Philippine Peso', symbol='₱'),
    Currency(code='AED', name='UAE Dirham', symbol='د.إ'),
    Currency(code='COP', name='Colombian Peso', symbol='$'),
    Currency(code='SAR', name='Saudi Riyal', symbol='﷼'),
    Currency(code='MYR', name='Malaysian Ringgit', symbol='RM'),
    Currency(code='RON', name='Romanian Leu', symbol='lei'),
    Currency(code='VND', name='Vietnamese Dong', symbol='₫'),
    Currency(code='EGP', name='Egyptian Pound', symbol='£'),
    Currency(code='PKR', name='Pakistani Rupee', symbol='₨'),
    Currency(code='NGN', name='Nigerian Naira', symbol='₦'),
    Currency(code='BDT', name='Bangladeshi Taka', symbol='৳'),
    Currency(code='KZT', name='Kazakhstani Tenge', symbol='₸'),
    Currency(code='UAH', name='Ukrainian Hryvnia', symbol='₴'),
    Currency(code='LKR', name='Sri Lankan Rupee', symbol='Rs'),
    Currency(code='KES', name='Kenyan Shilling', symbol='KSh'),
    Currency(code='MAD', name='Moroccan Dirham', symbol='د.م.'),
    Currency(code='DZD', name='Algerian Dinar', symbol='دج'),
    Currency(code='PEN', name='Peruvian Sol', symbol='S/'),
    Currency(code='ARS', name='Argentine Peso', symbol='$'),
    Currency(code='IQD', name='Iraqi Dinar', symbol='ع.د'),
])
