version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lonedash
      POSTGRES_USER: lonedash
      POSTGRES_PASSWORD: lonedash
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: lonedash
      POSTGRES_USER: lonedash
      POSTGRES_PASSWORD: lonedash
      POSTGRES_HOST: db

volumes:
  postgres_data:
