# Generated by Django 5.2.1 on 2025-06-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeentry',
            name='user',
        ),
    ]
