# Generated by Django 5.2.1 on 2025-05-30 07:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('security', 'Security')], max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='US', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=50)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('close', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('high', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('low', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('close', models.DecimalField(decimal_places=2, max_digits=16)),
                ('adjusted_close', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('volume', models.BigIntegerField(default=0)),
                ('security', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dash.security')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finhub_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('alpha_vantage_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('eodhd_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('yahoo_finance_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('google_map_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('dividien', 'Dividien'), ('interest', 'Interest'), ('fee', 'Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='dash.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='dash.account')),
            ],
            options={
                'unique_together': {('account', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='security',
            index=models.Index(fields=['user', 'code'], name='dash_securi_user_id_f8fb04_idx'),
        ),
        migrations.AddConstraint(
            model_name='security',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_user_code'),
        ),
        migrations.AddConstraint(
            model_name='securityprice',
            constraint=models.UniqueConstraint(fields=('security', 'date'), name='unique_security_date'),
        ),
    ]
