# Generated by Django 5.2.1 on 2025-05-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_country_currency_account_security_securityprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('broker', 'Broker')], max_length=255),
        ),
    ]
