# Generated by Django 5.2.1 on 2025-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_tradeentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioperformance',
            name='transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
