# Generated by Django 4.2.21 on 2025-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('dividien', 'Dividien'), ('interest', 'Interest'), ('fee', 'Fee'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=20),
        ),
    ]
