# Generated by Django 5.2.1 on 2025-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_portfolioperformance_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
