# Generated by Django 4.2.21 on 2025-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_transaction_fee_transaction_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
