# Generated by Django 5.2.1 on 2025-06-02 04:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_accountbalance_fee_accountbalance_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicdata',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('dividien', 'Dividien'), ('interest', 'Interest'), ('fee', 'Fee')], max_length=20),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='dash.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='dash.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
