# Generated by Django 3.2.19 on 2025-06-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_alter_economicdata_value_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
