# Generated by Django 5.2.1 on 2025-06-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_tradeentry_user_tradeexit_user_alter_security_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
