# Generated by Django 3.2.19 on 2025-06-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='alpha_vantage_api_key',
            new_name='key_alpha_vantage',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='eodhd_api_key',
            new_name='key_eodhd',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='finhub_api_key',
            new_name='key_finhub',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='google_map_api_key',
            new_name='key_google_map',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='yahoo_finance_api_key',
            new_name='key_yahoo',
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
