# Generated by Django 5.2.1 on 2025-06-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20250603_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='currency',
        ),
        migrations.AddField(
            model_name='security',
            name='api_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='dash.country'),
        ),
    ]
