# Generated by Django 5.2.1 on 2025-06-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_remove_security_currency_security_api_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
    ]
