# Generated by Django 5.2.1 on 2025-06-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_remove_trade_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='is_active',
        ),
    ]
