# Generated by Django 5.2.1 on 2025-06-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_remove_security_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='currency',
        ),
    ]
