# Generated by Django 5.2.1 on 2025-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_remove_trade_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='description',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
