# Generated by Django 5.2.1 on 2025-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_accountbalance_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='float',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
