# Generated by Django 5.2.1 on 2025-06-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_accountbalance_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='equity',
            new_name='principal',
        ),
    ]
