# Generated by Django 5.2.1 on 2025-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_rename_equity_accountbalance_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('dividien', 'Dividien'), ('interest', 'Interest'), ('fee', 'Fee')], max_length=20),
        ),
    ]
