# Generated by Django 5.2.1 on 2025-06-07 04:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprice',
            name='adjusted_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='securityprice',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('principal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('float', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='dash.account')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
