# Generated by Django 5.2.1 on 2025-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_alter_transaction_account_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeentry',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
        migrations.AlterField(
            model_name='tradeexit',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
